# Generated by Django 2.1.2 on 2019-02-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricity',
            old_name='customer_id',
            new_name='account_number',
        ),
    ]
