# Generated by Django 2.1.2 on 2019-02-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='owner',
        ),
    ]
