# Generated by Django 2.1.2 on 2019-02-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190218_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendoorlog',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
