# Generated by Django 2.1.2 on 2019-02-18 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_opendoorlog_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendoorlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
