# Generated by Django 2.1.2 on 2019-02-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190218_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendoorlog',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door', to='core.Door'),
        ),
    ]
